# .kodiak.toml
[merge.automerge_dependencies]
version = 1
# only auto merge "minor" and "patch" version upgrades.
# do not automerge "major" version upgrades.
versions = ["minor", "patch"]
usernames = ["dependabot", "renovate"]
merge.require_automerge_label = "automerge"
merge.delete_branch_on_merge = true
merge.blocking_labels = ["wip", "WIP"]