steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=Dockerfile
  - --destination=us-docker.pkg.dev/$PROJECT_ID/docker/phc-portal
  - --cache=true

options:
  machineType: 'N1_HIGHCPU_8'
