steps:
- name: 'alpine'
  args: ['sh', '-c', 'date +%s_$SHORT_SHA > _TAG']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -e  # Fail if any command below fails
    set -x  # Print commands
    docker build -t us-docker.pkg.dev/$PROJECT_ID/docker/phc-portal:$(cat _TAG) -t us-docker.pkg.dev/$PROJECT_ID/docker/phc-portal:latest .
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'us-docker.pkg.dev/$PROJECT_ID/docker/phc-portal:$(cat _TAG)'

images:
- 'us-docker.pkg.dev/$PROJECT_ID/docker/phc-portal:latest'
