steps:
- name: "gcr.io/kaniko-project/executor:latest"
  args:
    - --dockerfile=Dockerfile
    - --destination=us-docker.pkg.dev/$PROJECT_ID/docker/phc-portal:$SHORT_SHA
    - --snapshotMode=redo
    - --use-new-run=true
    - --cache=true
  waitFor: ['-']
  id: 'BUILD'

- name: 'us-docker.pkg.dev/$PROJECT_ID/docker/phc-docker-support/argocd'
  secretEnv: ['ARGOCD_ADMIN_PASSWORD']
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
    set -e  # Fail if any command below fails
    if [ $BRANCH_NAME != 'main' ]; then exit 0; fi
    argocd login cd.pluto.thepublichealthco.com --username admin --password $$ARGOCD_ADMIN_PASSWORD --grpc-web
    set -x  # Print commands
    argocd app set phc-portal -p phc-base.image.tag=$SHORT_SHA
    argocd app sync phc-portal
  waitFor:
  - 'BUILD'
  id: 'DEPLOY'

options:
  machineType: "N1_HIGHCPU_8"

availableSecrets:
  secretManager:
  - versionName: projects/139370234276/secrets/ARGOCD_ADMIN_PASSWORD/versions/1
    env: 'ARGOCD_ADMIN_PASSWORD'

