apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phc-portal
  name: phc-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phc-portal
  template:
    metadata:
      labels:
        app: phc-portal
    spec:
      containers:
      - name: phc-portal
        image: gcr.io/project-pluto-324014/phc-portal
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: phc-portal
  labels:
    run: phc-portal
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: phc-portal
