apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
spec:
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: phc-portal
        image: gcr.io/project-pluto-324014/phc-portal
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

