apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: gcr.io/project-pluto-324014/phc-portal
      docker:
        dockerfile: Dockerfile
        noCache: true
        cacheFrom:
          # googleCloudBuild replaces cache references to the artifact image with
          # the tagged image reference, useful for caching from the previous build.
          - gcr.io/project-pluto-324014/phc-portal
  googleCloudBuild:
    projectId: project-pluto-324014
    timeout: 1000s
    concurrency: 0
deploy:
  helm:
    releases:
      - name: phc-portal
        chartPath: helm/phc-portal
        artifactOverrides:
          phc-base.imageKey: gcr.io/project-pluto-324014/phc-portal
        namespace: 'rtillman'
        # namespace: "{{.SKAFFOLD_NAMESPACE}}"
        # Docs say to put this value in an envar,
        # but what does that mean in this context? I see no reference to env and I assume
        # it's not simply .env as with node.
        createNamespace: true
        valuesFiles:
          - 'helm/phc-portal/values.yaml'
        setValues:
          phc-base:
            skaffold: true
            imageConfig:
              pullPolicy: IfNotPresent
portForward:
  - resourceType: service
    resourceName: phc-portal
    namespace: 'rtillman'
    port: 8080
    localPort: 8081
# deploy:
#   kubectl:
#     manifests:
#       - "k8s/*.yaml"
