export const matchMedia = './lib/__mocks__/matchMedia'
export * from './lib/axiosMock'
export * from './lib/configPHC'
export * from './lib/environments/environment'
export * from './lib/getInitials'
export * from './lib/googleLibraries'
export * from './lib/test-utils'
export * from './lib/use-axios-api'
