phc-base:
  # helpers.tpl
  fullnameOverride: phc-portal

  # serviceaccount.yaml
#  serviceAccount:
#    annotations:
#      iam.gke.io/gcp-service-account: mdp-666@project-pluto-324014.iam.gserviceaccount.com

  # service.yaml
  service:
    annotations:
      cloud.googe.com/app-protocols: '{"phc-portal":"HTTPS"}'
      cloud.google.com/neg: '{"ingress": true}'
      cloud.google.com/backend-config: '{"default": "phc-portal"}'
    type: ClusterIP
    port: 3333
    ports:
      - port: 443
        targetPort: 3333
        protocol: TCP
        name: phc-portal

  # deployment.yaml
  replicaCount: 1
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/prometheus"
  image:
    repository: us-docker.pkg.dev/project-pluto-324014/docker/phc-portal
    tag: latest
    pullPolicy: Always
  readinessProbe:
    httpGet:
      path: /
      port: 3333
  livenessProbe:
    httpGet:
      path: /
      port: 3333
  autoscaling:
    enabled: false
  ports:
    - containerPort: 3333

  esp:
    enabled: false

  # backendconfig.yaml
  backendconfig:
    enabled: true
    type: HTTP
    requestPath: /
    port: 3333

  certificate:
    create: true
    commonName: "portal.pluto.thepublichealthco.com"
    secretName: esp-ssl
    issuer: selfsigned-dev
    issuerKind: ClusterIssuer

  managedCertificate:
    domains:
    - portal.pluto.thepublichealthco.com

  # ingress.yaml
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.allow-http: "false"
    tls:
    - hosts:
      - portal.pluto.thepublichealthco.com
    backend:
      serviceName: phc-portal
      servicePort: 443
