phc-base:
  # helpers.tpl
  fullnameOverride: phc-portal

  # serviceaccount.yaml
#  serviceAccount:
#    annotations:
#      iam.gke.io/gcp-service-account: mdp-666@project-pluto-324014.iam.gserviceaccount.com

  # service.yaml
  service:
    annotations:
      service.alpha.kubernetes.io/app-protocols: '{"phc-portal":"HTTP2"}'
      cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"443":{}}}'
      cloud.google.com/backend-config: '{"default": "phc-portal"}'
    type: ClusterIP
    port: 80
    ports:
      - port: 443
        targetPort: 9000
        protocol: TCP
        name: phc-portal

  # deployment.yaml
  replicaCount: 1
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/prometheus"
  image:
    repository: us-docker.pkg.dev/project-pluto-324014/docker/phc-portal
    tag: 89e869a-6db0e190-01b2-41a5-8d77-0424fc46f734
    pullPolicy: Always
  readinessProbe:
    httpGet:
      path: /
      port: 80
      httpHeaders:
      - name: Authorization
        value: Basic cGhjLWRlbW8tdXNlcjpwaGMuaGVhbHRoIHJ1bGVzIQ==
  livenessProbe:
    httpGet:
      path: /
      port: 80
      httpHeaders:
      - name: Authorization
        value: Basic cGhjLWRlbW8tdXNlcjpwaGMuaGVhbHRoIHJ1bGVzIQ==
  autoscaling:
    enabled: false
  ports:
    - containerPort: 80

  esp:
    enabled: true
    port: 9000
    service: portal.pluto.thepublichealthco.com
    targetPort: 80

  certificate:
    create: true
    commonName: "portal.pluto.thepublichealthco.com"
    secretName: esp-ssl
    issuer: selfsigned-dev
    issuerKind: ClusterIssuer

  # ingress.yaml
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.allow-http: "false"
    tls:
    - hosts:
      - portal.pluto.thepublichealthco.com
    backend:
      serviceName: phc-portal
      servicePort: 443
